language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
before_script:
  - cp .env-example .env
  - psql -c 'create database brief_ideas_test' -U postgres
  - bundle install
  - bundle exec rake db:schema:load

services:
  - redis-server

script: bundle exec rake
